### ISSUE TITLE
Detect if canvas exists before calling Browser canvas

### ISSUE THREAD

**Issue by interactivellama** [salesforce/design-system-react#1717]
v0.9.4 adds AppLauncher `Tile` component to the default export of the library. It uses the browser `HTMLCanvasElement` functionality. You may see errors in Jest tests now, since JSDOM does not implement Browser Canvas functionality.

Any calls to `HTMLCanvasElement` should be protected and only run if that object exists. Something like `if (canvas.getContext) {}`

https://github.com/salesforce/design-system-react/blob/master/components/utilities/truncate/index.jsx#L21

```
console.error node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/virtual-console.js:29
      Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)
          at module.exports (/Users/tswardenski/salesforce/repos/mce-eef-ui/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)
          at HTMLCanvasElementImpl.getContext (/Users/tswardenski/salesforce/repos/mce-eef-ui/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/nodes/HTMLCanvasElement-impl.js:42:5)
          at HTMLCanvasElement.getContext (/Users/tswardenski/salesforce/repos/mce-eef-ui/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/generated/HTMLCanvasElement.js:50:45)
          at Object.<anonymous> (/Users/tswardenski/salesforce/repos/mce-eef-ui/node_modules/@salesforce/design-system-react/lib/components/utilities/truncate/index.js:48:26)
          at Runtime._execModule (/Users/tswardenski/salesforce/repos/mce-eef-ui/node_modules/jest-runtime/build/index.js:694:13)
          at Runtime.requireModule (/Users/tswardenski/salesforce/repos/mce-eef-ui/node_modules/jest-runtime/build/index.js:376:14)
          at Runtime.requireModuleOrMock (/Users/tswardenski/salesforce/repos/mce-eef-ui/node_modules/jest-runtime/build/index.js:463:19)
          at Object.<anonymous> (/Users/tswardenski/salesforce/repos/mce-eef-ui/node_modules/@salesforce/design-system-react/lib/components/app-launcher/tile.js:23:17)
          at Runtime._execModule (/Users/tswardenski/salesforce/repos/mce-eef-ui/node_modules/jest-runtime/build/index.js:694:13)
          at Runtime.requireModule (/Users/tswardenski/salesforce/repos/mce-eef-ui/node_modules/jest-runtime/build/index.js:376:14) undefined
```

**Comment by pradumangoyal** [comment]
Hi @interactivellama, I am really interested in working on this issue. Can you please provide some more specifications on this issue.

**Comment by BenjaminWFox** [comment]
Do you have any update on this or workaround for preventing the errors while running tests?

**Comment by chriswilty** [comment]
+1 from me; reliance on canvas is annoying and potentially very confusing for those not using canvas. It would be seconds of work to add a check for canvas.getContext into the offending code in the truncate utility; I hate needing to add a devDependency just to silence this "error".

At the very least, you could document the need for jest-canvas-mock if people are writing (js-)dom-based tests.

**Comment by chriswilty** [comment]
Would it be unreasonable for me to open a PR for this trivial fix?
