### ISSUE TITLE
aXe testing results for new components/variants [0.10.3-0.10.6]

### ISSUE THREAD

**Issue by interactivellama** [salesforce/design-system-react#2164]
@jcjuett Passing except for `SLDSSetupAssistant` which has `id` issues which should be easy to fix.

```
aXe Testing
    aXe storyshots
      SLDSBuilderHeader
        ✓ Base (1632ms)
        ✓ Base with Toolbar (2333ms)
        ✓ Successful Save (2366ms)
        ✓ After Successful Save (2288ms)
        ✓ Failed Save (2341ms)
      SLDSButtonGroup
        ✓ More Icon (259ms)
        ✓ Icon Group (333ms)
        ✓ Checkbox (759ms)
        ✓ Checkbox Error (727ms)
        ✓ List Variant (345ms)
      SLDSExpandableSection
        ✓ Default (222ms)
        ✓ Controlled (220ms)
        ✓ Non-collapsible (102ms)
      SLDSProgressBar
        ✓ Default (109ms)
        ✓ Descriptive (165ms)
        ✓ Color (111ms)
        ✓ Radius (113ms)
        ✓ Thickness (384ms)
        ✓ Vertical (113ms)
      SLDSScopedNotification
        ✓ Base (164ms)
        ✓ Light (163ms)
        ✓ Dark (155ms)
      SLDSSetupAssistant
        ✓ Base Variant (1730ms)
        ✓ With Step Progress (2838ms)
        ✕ Hub with Expandable Steps (12340ms)
        ✕ In a Card (13436ms)
      SLDSTrialBar
        ✓ Default (294ms)
      SLDSVisualPicker
        ✓ Coverable (1992ms)
        ✓ Non-Coverable (2445ms)
        ✓ Links (461ms)
        ✓ Vertical (1950ms)
        ✓ Vertical Coverable (1880ms)

  ● aXe Testing › aXe storyshots › SLDSSetupAssistant › Hub with Expandable Steps

    expect(received).toHaveNoViolations(expected)

    Expected the HTML found at $('#hub-expandable-step-1 > article > .slds-summary-detail > .slds-button_icon.slds-m-right_x-small.slds-m-top_x-small') to have no violations:

    <button class="slds-button slds-button_icon slds-m-right_x-small slds-m-top_x-small" type="button" aria-controls="hub-expandable-step-1-detail-content">

    Expected the HTML found at $('.slds-is-open > .slds-button_icon.slds-m-right_x-small.slds-m-top_x-small') to have no violations:

    <button class="slds-button slds-button_icon slds-m-right_x-small slds-m-top_x-small" type="button" aria-controls="hub-expandable-step-2-detail-content">

    Expected the HTML found at $('#hub-expandable-step-3 > article > .slds-summary-detail > .slds-button_icon.slds-m-right_x-small.slds-m-top_x-small') to have no violations:

    <button class="slds-button slds-button_icon slds-m-right_x-small slds-m-top_x-small" type="button" aria-controls="hub-expandable-step-3-detail-content">

    Expected the HTML found at $('#hub-expandable-step-4 > article > .slds-summary-detail > .slds-button_icon.slds-m-right_x-small.slds-m-top_x-small') to have no violations:

    <button class="slds-button slds-button_icon slds-m-right_x-small slds-m-top_x-small" type="button" aria-controls="hub-expandable-step-4-detail-content">

    Expected the HTML found at $('#hub-expandable-step-5 > article > .slds-summary-detail > .slds-button_icon.slds-m-right_x-small.slds-m-top_x-small') to have no violations:

    <button class="slds-button slds-button_icon slds-m-right_x-small slds-m-top_x-small" type="button" aria-controls="hub-expandable-step-5-detail-content">

    Received:

    "Buttons must have discernible text (button-name)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/button-name?application=axeAPI

    ────────

    Expected the HTML found at $('#hub-expandable-step-1-progress-indicator > .slds-progress__list.slds-progress__list-bordered > .slds-is-completed.slds-progress__item:nth-child(2) > .slds-progress__item_content.slds-grid_align-spread.slds-grid > .slds-grid_align-end.slds-size_1-of-4.slds-grid > .slds-media__figure_reverse.slds-media__figure > .slds-text-link.slds-button_reset') to have no violations:

    <button class="slds-button_reset slds-text-link" id="substep-complete-1-action" type="button">View in Trailhead</button>

    Expected the HTML found at $('#hub-expandable-step-4-progress-indicator > .slds-progress__list.slds-progress__list-bordered > .slds-progress__item:nth-child(2) > .slds-progress__item_content.slds-grid_align-spread.slds-grid > .slds-grid_align-end.slds-size_1-of-4.slds-grid > .slds-media__figure_reverse.slds-media__figure > .slds-text-link.slds-button_reset') to have no violations:

    <button class="slds-button_reset slds-text-link" id="substep-incomplete-1-action" type="button">View in Trailhead</button>

    Received:

    "IDs of active elements must be unique (duplicate-id-active)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/duplicate-id-active?application=axeAPI

    ────────

    Expected the HTML found at $('#hub-expandable-step-1-progress-indicator > .slds-progress__list.slds-progress__list-bordered > .slds-is-completed.slds-is-active.slds-progress__item > .slds-progress__item_content.slds-grid_align-spread.slds-grid > .slds-grid_align-end.slds-size_1-of-4.slds-grid > .slds-media__figure_reverse.slds-media__figure > .slds-form-element > label[for="substep-complete-0-action"] > input[aria-describedby="substep-complete-0-action-desc"]') to have no violations:

    <input aria-describedby="substep-complete-0-action-desc" id="substep-complete-0-action" type="checkbox" checked="">

    Expected the HTML found at $('#hub-expandable-step-1-progress-indicator > .slds-progress__list.slds-progress__list-bordered > .slds-is-completed.slds-is-active.slds-progress__item > .slds-progress__item_content.slds-grid_align-spread.slds-grid > .slds-grid_align-end.slds-size_1-of-4.slds-grid > .slds-media__figure_reverse.slds-media__figure > .slds-form-element > label[for="substep-complete-0-action"] > .slds-checkbox_faux_container[aria-live="assertive"]') to have no violations:

    <span id="substep-complete-0-action-desc" class="slds-checkbox_faux_container" aria-live="assertive"><span class="slds-checkbox_faux"></span><span class="slds-checkbox_on">Enabled</span><span class="slds-checkbox_off">Disabled</span></span>

    Expected the HTML found at $('#hub-expandable-step-4-progress-indicator > .slds-progress__list.slds-progress__list-bordered > .slds-is-active.slds-progress__item > .slds-progress__item_content.slds-grid_align-spread.slds-grid > .slds-grid_align-end.slds-size_1-of-4.slds-grid > .slds-media__figure_reverse.slds-media__figure > .slds-form-element > label[for="substep-incomplete-0-action"] > input') to have no violations:

    <input aria-describedby="substep-incomplete-0-action-desc" id="substep-incomplete-0-action" type="checkbox">

    Expected the HTML found at $('#hub-expandable-step-4-progress-indicator > .slds-progress__list.slds-progress__list-bordered > .slds-is-active.slds-progress__item > .slds-progress__item_content.slds-grid_align-spread.slds-grid > .slds-grid_align-end.slds-size_1-of-4.slds-grid > .slds-media__figure_reverse.slds-media__figure > .slds-form-element > label[for="substep-incomplete-0-action"] > .slds-checkbox_faux_container[aria-live="assertive"]') to have no violations:

    <span id="substep-incomplete-0-action-desc" class="slds-checkbox_faux_container" aria-live="assertive"><span class="slds-checkbox_faux"></span><span class="slds-checkbox_on">Enabled</span><span class="slds-checkbox_off">Disabled</span></span>

    Received:

    "IDs used in ARIA and labels must be unique (duplicate-id-aria)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/duplicate-id-aria?application=axeAPI

    ────────

    Expected the HTML found at $('#hub-expandable-step-1-progress-indicator > .slds-progress__list.slds-progress__list-bordered > .slds-is-completed.slds-is-active.slds-progress__item > .slds-progress__item_content.slds-grid_align-spread.slds-grid') to have no violations:

    <div id="progress-indicator-vertical-label-0" class="slds-progress__item_content slds-grid slds-grid_align-spread">

    Expected the HTML found at $('#hub-expandable-step-1-progress-indicator > .slds-progress__list.slds-progress__list-bordered > .slds-is-completed.slds-progress__item:nth-child(2) > .slds-progress__item_content.slds-grid_align-spread.slds-grid') to have no violations:

    <div id="progress-indicator-vertical-label-1" class="slds-progress__item_content slds-grid slds-grid_align-spread">

    Received:

    "id attribute value must be unique (duplicate-id)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/duplicate-id?application=axeAPI

    ────────

    Expected the HTML found at $('#hub-expandable-step-1-progress-indicator > .slds-progress__list.slds-progress__list-bordered > .slds-is-completed.slds-is-active.slds-progress__item > .slds-progress__item_content.slds-grid_align-spread.slds-grid > .slds-grid_align-end.slds-size_1-of-4.slds-grid > .slds-media__figure_reverse.slds-media__figure > .slds-form-element > label[for="substep-complete-0-action"] > input[aria-describedby="substep-complete-0-action-desc"]') to have no violations:

    <input aria-describedby="substep-complete-0-action-desc" id="substep-complete-0-action" type="checkbox" checked="">

    Expected the HTML found at $('#hub-expandable-step-3-progress-indicator > .slds-progress__list.slds-progress__list-bordered > .slds-is-completed.slds-is-active.slds-progress__item > .slds-progress__item_content.slds-grid_align-spread.slds-grid > .slds-grid_align-end.slds-size_1-of-4.slds-grid > .slds-media__figure_reverse.slds-media__figure > .slds-form-element > label[for="substep-complete-0-action"] > input[aria-describedby="substep-complete-0-action-desc"]') to have no violations:

    <input aria-describedby="substep-complete-0-action-desc" id="substep-complete-0-action" type="checkbox" checked="">

    Expected the HTML found at $('#hub-expandable-step-4-progress-indicator > .slds-progress__list.slds-progress__list-bordered > .slds-is-active.slds-progress__item > .slds-progress__item_content.slds-grid_align-spread.slds-grid > .slds-grid_align-end.slds-size_1-of-4.slds-grid > .slds-media__figure_reverse.slds-media__figure > .slds-form-element > label[for="substep-incomplete-0-action"] > input') to have no violations:

    <input aria-describedby="substep-incomplete-0-action-desc" id="substep-incomplete-0-action" type="checkbox">

    Expected the HTML found at $('#hub-expandable-step-5-progress-indicator > .slds-progress__list.slds-progress__list-bordered > .slds-is-active.slds-progress__item > .slds-progress__item_content.slds-grid_align-spread.slds-grid > .slds-grid_align-end.slds-size_1-of-4.slds-grid > .slds-media__figure_reverse.slds-media__figure > .slds-form-element > label[for="substep-incomplete-0-action"] > input') to have no violations:

    <input aria-describedby="substep-incomplete-0-action-desc" id="substep-incomplete-0-action" type="checkbox">

    Received:

    "Form field must not have multiple label elements (form-field-multiple-labels)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/form-field-multiple-labels?application=axeAPI

      85 | 					},
      86 | 				})
    > 87 | 			).toHaveNoViolations();
         | 			  ^
      88 | 		},
      89 | 	});
      90 | });

      at _callee$ (tests/story-based-tests.accessibility-test.js:87:6)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (tests/story-based-tests.accessibility-test.js:32:103)
      at _next (tests/story-based-tests.accessibility-test.js:34:194)

  ● aXe Testing › aXe storyshots › SLDSSetupAssistant › In a Card

    expect(received).toHaveNoViolations(expected)

    Expected the HTML found at $('.slds-button_icon.slds-m-right_x-small[aria-controls="card-step-1-detail-content"]') to have no violations:

    <button class="slds-button slds-button_icon slds-m-right_x-small slds-m-top_x-small" type="button" aria-controls="card-step-1-detail-content">

    Expected the HTML found at $('.slds-button_icon.slds-m-right_x-small[aria-controls="card-step-2-detail-content"]') to have no violations:

    <button class="slds-button slds-button_icon slds-m-right_x-small slds-m-top_x-small" type="button" aria-controls="card-step-2-detail-content">

    Expected the HTML found at $('.slds-button_icon.slds-m-right_x-small[aria-controls="card-step-3-detail-content"]') to have no violations:

    <button class="slds-button slds-button_icon slds-m-right_x-small slds-m-top_x-small" type="button" aria-controls="card-step-3-detail-content">

    Expected the HTML found at $('.slds-button_icon.slds-m-right_x-small[aria-controls="card-step-4-detail-content"]') to have no violations:

    <button class="slds-button slds-button_icon slds-m-right_x-small slds-m-top_x-small" type="button" aria-controls="card-step-4-detail-content">

    Expected the HTML found at $('.slds-button_icon.slds-m-right_x-small[aria-controls="card-step-5-detail-content"]') to have no violations:

    <button class="slds-button slds-button_icon slds-m-right_x-small slds-m-top_x-small" type="button" aria-controls="card-step-5-detail-content">

    Received:

    "Buttons must have discernible text (button-name)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/button-name?application=axeAPI

    ────────

    Expected the HTML found at $('#card-step-1-progress-indicator > .slds-progress__list.slds-progress__list-bordered > .slds-is-completed.slds-progress__item:nth-child(2) > .slds-progress__item_content.slds-grid_align-spread.slds-grid > .slds-grid_align-end.slds-size_1-of-4.slds-grid > .slds-media__figure_reverse.slds-media__figure > .slds-text-link.slds-button_reset') to have no violations:

    <button class="slds-button_reset slds-text-link" id="substep-complete-1-action" type="button">View in Trailhead</button>

    Expected the HTML found at $('#card-step-4-progress-indicator > .slds-progress__list.slds-progress__list-bordered > .slds-progress__item:nth-child(2) > .slds-progress__item_content.slds-grid_align-spread.slds-grid > .slds-grid_align-end.slds-size_1-of-4.slds-grid > .slds-media__figure_reverse.slds-media__figure > .slds-text-link.slds-button_reset') to have no violations:

    <button class="slds-button_reset slds-text-link" id="substep-incomplete-1-action" type="button">View in Trailhead</button>

    Received:

    "IDs of active elements must be unique (duplicate-id-active)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/duplicate-id-active?application=axeAPI

    ────────

    Expected the HTML found at $('#card-step-1-progress-indicator > .slds-progress__list.slds-progress__list-bordered > .slds-is-completed.slds-is-active.slds-progress__item > .slds-progress__item_content.slds-grid_align-spread.slds-grid > .slds-grid_align-end.slds-size_1-of-4.slds-grid > .slds-media__figure_reverse.slds-media__figure > .slds-form-element > label[for="substep-complete-0-action"] > input[aria-describedby="substep-complete-0-action-desc"]') to have no violations:

    <input aria-describedby="substep-complete-0-action-desc" id="substep-complete-0-action" type="checkbox" checked="">

    Expected the HTML found at $('#card-step-1-progress-indicator > .slds-progress__list.slds-progress__list-bordered > .slds-is-completed.slds-is-active.slds-progress__item > .slds-progress__item_content.slds-grid_align-spread.slds-grid > .slds-grid_align-end.slds-size_1-of-4.slds-grid > .slds-media__figure_reverse.slds-media__figure > .slds-form-element > label[for="substep-complete-0-action"] > .slds-checkbox_faux_container[aria-live="assertive"]') to have no violations:

    <span id="substep-complete-0-action-desc" class="slds-checkbox_faux_container" aria-live="assertive"><span class="slds-checkbox_faux"></span><span class="slds-checkbox_on">Enabled</span><span class="slds-checkbox_off">Disabled</span></span>

    Expected the HTML found at $('#card-step-4-progress-indicator > .slds-progress__list.slds-progress__list-bordered > .slds-is-active.slds-progress__item > .slds-progress__item_content.slds-grid_align-spread.slds-grid > .slds-grid_align-end.slds-size_1-of-4.slds-grid > .slds-media__figure_reverse.slds-media__figure > .slds-form-element > label[for="substep-incomplete-0-action"] > input') to have no violations:

    <input aria-describedby="substep-incomplete-0-action-desc" id="substep-incomplete-0-action" type="checkbox">

    Expected the HTML found at $('#card-step-4-progress-indicator > .slds-progress__list.slds-progress__list-bordered > .slds-is-active.slds-progress__item > .slds-progress__item_content.slds-grid_align-spread.slds-grid > .slds-grid_align-end.slds-size_1-of-4.slds-grid > .slds-media__figure_reverse.slds-media__figure > .slds-form-element > label[for="substep-incomplete-0-action"] > .slds-checkbox_faux_container[aria-live="assertive"]') to have no violations:

    <span id="substep-incomplete-0-action-desc" class="slds-checkbox_faux_container" aria-live="assertive"><span class="slds-checkbox_faux"></span><span class="slds-checkbox_on">Enabled</span><span class="slds-checkbox_off">Disabled</span></span>

    Received:

    "IDs used in ARIA and labels must be unique (duplicate-id-aria)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/duplicate-id-aria?application=axeAPI

    ────────

    Expected the HTML found at $('#card-step-1-progress-indicator > .slds-progress__list.slds-progress__list-bordered > .slds-is-completed.slds-is-active.slds-progress__item > .slds-progress__item_content.slds-grid_align-spread.slds-grid') to have no violations:

    <div id="progress-indicator-vertical-label-0" class="slds-progress__item_content slds-grid slds-grid_align-spread">

    Expected the HTML found at $('#card-step-1-progress-indicator > .slds-progress__list.slds-progress__list-bordered > .slds-is-completed.slds-progress__item:nth-child(2) > .slds-progress__item_content.slds-grid_align-spread.slds-grid') to have no violations:

    <div id="progress-indicator-vertical-label-1" class="slds-progress__item_content slds-grid slds-grid_align-spread">

    Received:

    "id attribute value must be unique (duplicate-id)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/duplicate-id?application=axeAPI

    ────────

    Expected the HTML found at $('#card-step-1-progress-indicator > .slds-progress__list.slds-progress__list-bordered > .slds-is-completed.slds-is-active.slds-progress__item > .slds-progress__item_content.slds-grid_align-spread.slds-grid > .slds-grid_align-end.slds-size_1-of-4.slds-grid > .slds-media__figure_reverse.slds-media__figure > .slds-form-element > label[for="substep-complete-0-action"] > input[aria-describedby="substep-complete-0-action-desc"]') to have no violations:

    <input aria-describedby="substep-complete-0-action-desc" id="substep-complete-0-action" type="checkbox" checked="">

    Expected the HTML found at $('#card-step-3-progress-indicator > .slds-progress__list.slds-progress__list-bordered > .slds-is-completed.slds-is-active.slds-progress__item > .slds-progress__item_content.slds-grid_align-spread.slds-grid > .slds-grid_align-end.slds-size_1-of-4.slds-grid > .slds-media__figure_reverse.slds-media__figure > .slds-form-element > label[for="substep-complete-0-action"] > input[aria-describedby="substep-complete-0-action-desc"]') to have no violations:

    <input aria-describedby="substep-complete-0-action-desc" id="substep-complete-0-action" type="checkbox" checked="">

    Expected the HTML found at $('#card-step-4-progress-indicator > .slds-progress__list.slds-progress__list-bordered > .slds-is-active.slds-progress__item > .slds-progress__item_content.slds-grid_align-spread.slds-grid > .slds-grid_align-end.slds-size_1-of-4.slds-grid > .slds-media__figure_reverse.slds-media__figure > .slds-form-element > label[for="substep-incomplete-0-action"] > input') to have no violations:

    <input aria-describedby="substep-incomplete-0-action-desc" id="substep-incomplete-0-action" type="checkbox">

    Expected the HTML found at $('#card-step-5-progress-indicator > .slds-progress__list.slds-progress__list-bordered > .slds-is-active.slds-progress__item > .slds-progress__item_content.slds-grid_align-spread.slds-grid > .slds-grid_align-end.slds-size_1-of-4.slds-grid > .slds-media__figure_reverse.slds-media__figure > .slds-form-element > label[for="substep-incomplete-0-action"] > input') to have no violations:

    <input aria-describedby="substep-incomplete-0-action-desc" id="substep-incomplete-0-action" type="checkbox">

    Received:

    "Form field must not have multiple label elements (form-field-multiple-labels)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/form-field-multiple-labels?application=axeAPI

      85 | 					},
      86 | 				})
    > 87 | 			).toHaveNoViolations();
         | 			  ^
      88 | 		},
      89 | 	});
      90 | });

      at _callee$ (tests/story-based-tests.accessibility-test.js:87:6)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (tests/story-based-tests.accessibility-test.js:32:103)
      at _next (tests/story-based-tests.accessibility-test.js:34:194)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 30 passed, 32 total
Snapshots:   0 total
Time:        81.978s
Ran all test suites.

```

**Comment by interactivellama** [comment]
@jcjuett I'm going to close this one now since these are passing except `SetupAssistant`
