### ISSUE TITLE
Make Setup Assistant pass aXe accessibility testing

### ISSUE THREAD

**Issue by interactivellama** [salesforce/design-system-react#2165]
### Issues
* "Buttons must have discernible text (button-name)" - These appear to be the expand buttons. Please add `assistiveText.toggleStepDetails` key.
*  "IDs of active elements must be unique (duplicate-id-active)" and the rest of the issues - These are just duplicate ids in the example and need to be different.

### Full results

```
aXe Testing
    aXe storyshots
      SLDSSetupAssistant
        ✓ Base Variant (1974ms)
        ✓ With Step Progress (2866ms)
        ✕ Hub with Expandable Steps (12002ms)
        ✕ In a Card (12927ms)

  ● aXe Testing › aXe storyshots › SLDSSetupAssistant › Hub with Expandable Steps

    expect(received).toHaveNoViolations(expected)

    Expected the HTML found at $('#hub-expandable-step-1 > article > .slds-summary-detail > .slds-button_icon.slds-m-right_x-small.slds-m-top_x-small') to have no violations:

    <button class="slds-button slds-button_icon slds-m-right_x-small slds-m-top_x-small" type="button" aria-controls="hub-expandable-step-1-detail-content">

    Expected the HTML found at $('.slds-is-open > .slds-button_icon.slds-m-right_x-small.slds-m-top_x-small') to have no violations:

    <button class="slds-button slds-button_icon slds-m-right_x-small slds-m-top_x-small" type="button" aria-controls="hub-expandable-step-2-detail-content">

    Expected the HTML found at $('#hub-expandable-step-3 > article > .slds-summary-detail > .slds-button_icon.slds-m-right_x-small.slds-m-top_x-small') to have no violations:

    <button class="slds-button slds-button_icon slds-m-right_x-small slds-m-top_x-small" type="button" aria-controls="hub-expandable-step-3-detail-content">

    Expected the HTML found at $('#hub-expandable-step-4 > article > .slds-summary-detail > .slds-button_icon.slds-m-right_x-small.slds-m-top_x-small') to have no violations:

    <button class="slds-button slds-button_icon slds-m-right_x-small slds-m-top_x-small" type="button" aria-controls="hub-expandable-step-4-detail-content">

    Expected the HTML found at $('#hub-expandable-step-5 > article > .slds-summary-detail > .slds-button_icon.slds-m-right_x-small.slds-m-top_x-small') to have no violations:

    <button class="slds-button slds-button_icon slds-m-right_x-small slds-m-top_x-small" type="button" aria-controls="hub-expandable-step-5-detail-content">

    Received:

    "Buttons must have discernible text (button-name)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/button-name?application=axeAPI

    ────────

    Expected the HTML found at $('#hub-expandable-step-1-progress-indicator > .slds-progress__list.slds-progress__list-bordered > .slds-is-completed.slds-progress__item:nth-child(2) > .slds-progress__item_content.slds-grid_align-spread.slds-grid > .slds-grid_align-end.slds-size_1-of-4.slds-grid > .slds-media__figure_reverse.slds-media__figure > .slds-text-link.slds-button_reset') to have no violations:

    <button class="slds-button_reset slds-text-link" id="substep-complete-1-action" type="button">View in Trailhead</button>

    Expected the HTML found at $('#hub-expandable-step-4-progress-indicator > .slds-progress__list.slds-progress__list-bordered > .slds-progress__item:nth-child(2) > .slds-progress__item_content.slds-grid_align-spread.slds-grid > .slds-grid_align-end.slds-size_1-of-4.slds-grid > .slds-media__figure_reverse.slds-media__figure > .slds-text-link.slds-button_reset') to have no violations:

    <button class="slds-button_reset slds-text-link" id="substep-incomplete-1-action" type="button">View in Trailhead</button>

    Received:

    "IDs of active elements must be unique (duplicate-id-active)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/duplicate-id-active?application=axeAPI

    ────────

    Expected the HTML found at $('#hub-expandable-step-1-progress-indicator > .slds-progress__list.slds-progress__list-bordered > .slds-is-completed.slds-is-active.slds-progress__item > .slds-progress__item_content.slds-grid_align-spread.slds-grid > .slds-grid_align-end.slds-size_1-of-4.slds-grid > .slds-media__figure_reverse.slds-media__figure > .slds-form-element > label[for="substep-complete-0-action"] > input[aria-describedby="substep-complete-0-action-desc"]') to have no violations:

    <input aria-describedby="substep-complete-0-action-desc" id="substep-complete-0-action" type="checkbox" checked="">

    Expected the HTML found at $('#hub-expandable-step-1-progress-indicator > .slds-progress__list.slds-progress__list-bordered > .slds-is-completed.slds-is-active.slds-progress__item > .slds-progress__item_content.slds-grid_align-spread.slds-grid > .slds-grid_align-end.slds-size_1-of-4.slds-grid > .slds-media__figure_reverse.slds-media__figure > .slds-form-element > label[for="substep-complete-0-action"] > .slds-checkbox_faux_container[aria-live="assertive"]') to have no violations:

    <span id="substep-complete-0-action-desc" class="slds-checkbox_faux_container" aria-live="assertive"><span class="slds-checkbox_faux"></span><span class="slds-checkbox_on">Enabled</span><span class="slds-checkbox_off">Disabled</span></span>

    Expected the HTML found at $('#hub-expandable-step-4-progress-indicator > .slds-progress__list.slds-progress__list-bordered > .slds-is-active.slds-progress__item > .slds-progress__item_content.slds-grid_align-spread.slds-grid > .slds-grid_align-end.slds-size_1-of-4.slds-grid > .slds-media__figure_reverse.slds-media__figure > .slds-form-element > label[for="substep-incomplete-0-action"] > input') to have no violations:

    <input aria-describedby="substep-incomplete-0-action-desc" id="substep-incomplete-0-action" type="checkbox">

    Expected the HTML found at $('#hub-expandable-step-4-progress-indicator > .slds-progress__list.slds-progress__list-bordered > .slds-is-active.slds-progress__item > .slds-progress__item_content.slds-grid_align-spread.slds-grid > .slds-grid_align-end.slds-size_1-of-4.slds-grid > .slds-media__figure_reverse.slds-media__figure > .slds-form-element > label[for="substep-incomplete-0-action"] > .slds-checkbox_faux_container[aria-live="assertive"]') to have no violations:

    <span id="substep-incomplete-0-action-desc" class="slds-checkbox_faux_container" aria-live="assertive"><span class="slds-checkbox_faux"></span><span class="slds-checkbox_on">Enabled</span><span class="slds-checkbox_off">Disabled</span></span>

    Received:

    "IDs used in ARIA and labels must be unique (duplicate-id-aria)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/duplicate-id-aria?application=axeAPI

    ────────

    Expected the HTML found at $('#hub-expandable-step-1-progress-indicator > .slds-progress__list.slds-progress__list-bordered > .slds-is-completed.slds-is-active.slds-progress__item > .slds-progress__item_content.slds-grid_align-spread.slds-grid') to have no violations:

    <div id="progress-indicator-vertical-label-0" class="slds-progress__item_content slds-grid slds-grid_align-spread">

    Expected the HTML found at $('#hub-expandable-step-1-progress-indicator > .slds-progress__list.slds-progress__list-bordered > .slds-is-completed.slds-progress__item:nth-child(2) > .slds-progress__item_content.slds-grid_align-spread.slds-grid') to have no violations:

    <div id="progress-indicator-vertical-label-1" class="slds-progress__item_content slds-grid slds-grid_align-spread">

    Received:

    "id attribute value must be unique (duplicate-id)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/duplicate-id?application=axeAPI

    ────────

    Expected the HTML found at $('#hub-expandable-step-1-progress-indicator > .slds-progress__list.slds-progress__list-bordered > .slds-is-completed.slds-is-active.slds-progress__item > .slds-progress__item_content.slds-grid_align-spread.slds-grid > .slds-grid_align-end.slds-size_1-of-4.slds-grid > .slds-media__figure_reverse.slds-media__figure > .slds-form-element > label[for="substep-complete-0-action"] > input[aria-describedby="substep-complete-0-action-desc"]') to have no violations:

    <input aria-describedby="substep-complete-0-action-desc" id="substep-complete-0-action" type="checkbox" checked="">

    Expected the HTML found at $('#hub-expandable-step-3-progress-indicator > .slds-progress__list.slds-progress__list-bordered > .slds-is-completed.slds-is-active.slds-progress__item > .slds-progress__item_content.slds-grid_align-spread.slds-grid > .slds-grid_align-end.slds-size_1-of-4.slds-grid > .slds-media__figure_reverse.slds-media__figure > .slds-form-element > label[for="substep-complete-0-action"] > input[aria-describedby="substep-complete-0-action-desc"]') to have no violations:

    <input aria-describedby="substep-complete-0-action-desc" id="substep-complete-0-action" type="checkbox" checked="">

    Expected the HTML found at $('#hub-expandable-step-4-progress-indicator > .slds-progress__list.slds-progress__list-bordered > .slds-is-active.slds-progress__item > .slds-progress__item_content.slds-grid_align-spread.slds-grid > .slds-grid_align-end.slds-size_1-of-4.slds-grid > .slds-media__figure_reverse.slds-media__figure > .slds-form-element > label[for="substep-incomplete-0-action"] > input') to have no violations:

    <input aria-describedby="substep-incomplete-0-action-desc" id="substep-incomplete-0-action" type="checkbox">

    Expected the HTML found at $('#hub-expandable-step-5-progress-indicator > .slds-progress__list.slds-progress__list-bordered > .slds-is-active.slds-progress__item > .slds-progress__item_content.slds-grid_align-spread.slds-grid > .slds-grid_align-end.slds-size_1-of-4.slds-grid > .slds-media__figure_reverse.slds-media__figure > .slds-form-element > label[for="substep-incomplete-0-action"] > input') to have no violations:

    <input aria-describedby="substep-incomplete-0-action-desc" id="substep-incomplete-0-action" type="checkbox">

    Received:

    "Form field must not have multiple label elements (form-field-multiple-labels)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/form-field-multiple-labels?application=axeAPI

      85 | 					},
      86 | 				})
    > 87 | 			).toHaveNoViolations();
         | 			  ^
      88 | 		},
      89 | 	});
      90 | });

      at _callee$ (tests/story-based-tests.accessibility-test.js:87:6)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (tests/story-based-tests.accessibility-test.js:32:103)
      at _next (tests/story-based-tests.accessibility-test.js:34:194)

  ● aXe Testing › aXe storyshots › SLDSSetupAssistant › In a Card

    expect(received).toHaveNoViolations(expected)

    Expected the HTML found at $('.slds-button_icon.slds-m-right_x-small[aria-controls="card-step-1-detail-content"]') to have no violations:

    <button class="slds-button slds-button_icon slds-m-right_x-small slds-m-top_x-small" type="button" aria-controls="card-step-1-detail-content">

    Expected the HTML found at $('.slds-button_icon.slds-m-right_x-small[aria-controls="card-step-2-detail-content"]') to have no violations:

    <button class="slds-button slds-button_icon slds-m-right_x-small slds-m-top_x-small" type="button" aria-controls="card-step-2-detail-content">

    Expected the HTML found at $('.slds-button_icon.slds-m-right_x-small[aria-controls="card-step-3-detail-content"]') to have no violations:

    <button class="slds-button slds-button_icon slds-m-right_x-small slds-m-top_x-small" type="button" aria-controls="card-step-3-detail-content">

    Expected the HTML found at $('.slds-button_icon.slds-m-right_x-small[aria-controls="card-step-4-detail-content"]') to have no violations:

    <button class="slds-button slds-button_icon slds-m-right_x-small slds-m-top_x-small" type="button" aria-controls="card-step-4-detail-content">

    Expected the HTML found at $('.slds-button_icon.slds-m-right_x-small[aria-controls="card-step-5-detail-content"]') to have no violations:

    <button class="slds-button slds-button_icon slds-m-right_x-small slds-m-top_x-small" type="button" aria-controls="card-step-5-detail-content">

    Received:

    "Buttons must have discernible text (button-name)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/button-name?application=axeAPI

    ────────

    Expected the HTML found at $('#card-step-1-progress-indicator > .slds-progress__list.slds-progress__list-bordered > .slds-is-completed.slds-progress__item:nth-child(2) > .slds-progress__item_content.slds-grid_align-spread.slds-grid > .slds-grid_align-end.slds-size_1-of-4.slds-grid > .slds-media__figure_reverse.slds-media__figure > .slds-text-link.slds-button_reset') to have no violations:

    <button class="slds-button_reset slds-text-link" id="substep-complete-1-action" type="button">View in Trailhead</button>

    Expected the HTML found at $('#card-step-4-progress-indicator > .slds-progress__list.slds-progress__list-bordered > .slds-progress__item:nth-child(2) > .slds-progress__item_content.slds-grid_align-spread.slds-grid > .slds-grid_align-end.slds-size_1-of-4.slds-grid > .slds-media__figure_reverse.slds-media__figure > .slds-text-link.slds-button_reset') to have no violations:

    <button class="slds-button_reset slds-text-link" id="substep-incomplete-1-action" type="button">View in Trailhead</button>

    Received:

    "IDs of active elements must be unique (duplicate-id-active)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/duplicate-id-active?application=axeAPI

    ────────

    Expected the HTML found at $('#card-step-1-progress-indicator > .slds-progress__list.slds-progress__list-bordered > .slds-is-completed.slds-is-active.slds-progress__item > .slds-progress__item_content.slds-grid_align-spread.slds-grid > .slds-grid_align-end.slds-size_1-of-4.slds-grid > .slds-media__figure_reverse.slds-media__figure > .slds-form-element > label[for="substep-complete-0-action"] > input[aria-describedby="substep-complete-0-action-desc"]') to have no violations:

    <input aria-describedby="substep-complete-0-action-desc" id="substep-complete-0-action" type="checkbox" checked="">

    Expected the HTML found at $('#card-step-1-progress-indicator > .slds-progress__list.slds-progress__list-bordered > .slds-is-completed.slds-is-active.slds-progress__item > .slds-progress__item_content.slds-grid_align-spread.slds-grid > .slds-grid_align-end.slds-size_1-of-4.slds-grid > .slds-media__figure_reverse.slds-media__figure > .slds-form-element > label[for="substep-complete-0-action"] > .slds-checkbox_faux_container[aria-live="assertive"]') to have no violations:

    <span id="substep-complete-0-action-desc" class="slds-checkbox_faux_container" aria-live="assertive"><span class="slds-checkbox_faux"></span><span class="slds-checkbox_on">Enabled</span><span class="slds-checkbox_off">Disabled</span></span>

    Expected the HTML found at $('#card-step-4-progress-indicator > .slds-progress__list.slds-progress__list-bordered > .slds-is-active.slds-progress__item > .slds-progress__item_content.slds-grid_align-spread.slds-grid > .slds-grid_align-end.slds-size_1-of-4.slds-grid > .slds-media__figure_reverse.slds-media__figure > .slds-form-element > label[for="substep-incomplete-0-action"] > input') to have no violations:

    <input aria-describedby="substep-incomplete-0-action-desc" id="substep-incomplete-0-action" type="checkbox">

    Expected the HTML found at $('#card-step-4-progress-indicator > .slds-progress__list.slds-progress__list-bordered > .slds-is-active.slds-progress__item > .slds-progress__item_content.slds-grid_align-spread.slds-grid > .slds-grid_align-end.slds-size_1-of-4.slds-grid > .slds-media__figure_reverse.slds-media__figure > .slds-form-element > label[for="substep-incomplete-0-action"] > .slds-checkbox_faux_container[aria-live="assertive"]') to have no violations:

    <span id="substep-incomplete-0-action-desc" class="slds-checkbox_faux_container" aria-live="assertive"><span class="slds-checkbox_faux"></span><span class="slds-checkbox_on">Enabled</span><span class="slds-checkbox_off">Disabled</span></span>

    Received:

    "IDs used in ARIA and labels must be unique (duplicate-id-aria)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/duplicate-id-aria?application=axeAPI

    ────────

    Expected the HTML found at $('#card-step-1-progress-indicator > .slds-progress__list.slds-progress__list-bordered > .slds-is-completed.slds-is-active.slds-progress__item > .slds-progress__item_content.slds-grid_align-spread.slds-grid') to have no violations:

    <div id="progress-indicator-vertical-label-0" class="slds-progress__item_content slds-grid slds-grid_align-spread">

    Expected the HTML found at $('#card-step-1-progress-indicator > .slds-progress__list.slds-progress__list-bordered > .slds-is-completed.slds-progress__item:nth-child(2) > .slds-progress__item_content.slds-grid_align-spread.slds-grid') to have no violations:

    <div id="progress-indicator-vertical-label-1" class="slds-progress__item_content slds-grid slds-grid_align-spread">

    Received:

    "id attribute value must be unique (duplicate-id)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/duplicate-id?application=axeAPI

    ────────

    Expected the HTML found at $('#card-step-1-progress-indicator > .slds-progress__list.slds-progress__list-bordered > .slds-is-completed.slds-is-active.slds-progress__item > .slds-progress__item_content.slds-grid_align-spread.slds-grid > .slds-grid_align-end.slds-size_1-of-4.slds-grid > .slds-media__figure_reverse.slds-media__figure > .slds-form-element > label[for="substep-complete-0-action"] > input[aria-describedby="substep-complete-0-action-desc"]') to have no violations:

    <input aria-describedby="substep-complete-0-action-desc" id="substep-complete-0-action" type="checkbox" checked="">

    Expected the HTML found at $('#card-step-3-progress-indicator > .slds-progress__list.slds-progress__list-bordered > .slds-is-completed.slds-is-active.slds-progress__item > .slds-progress__item_content.slds-grid_align-spread.slds-grid > .slds-grid_align-end.slds-size_1-of-4.slds-grid > .slds-media__figure_reverse.slds-media__figure > .slds-form-element > label[for="substep-complete-0-action"] > input[aria-describedby="substep-complete-0-action-desc"]') to have no violations:

    <input aria-describedby="substep-complete-0-action-desc" id="substep-complete-0-action" type="checkbox" checked="">

    Expected the HTML found at $('#card-step-4-progress-indicator > .slds-progress__list.slds-progress__list-bordered > .slds-is-active.slds-progress__item > .slds-progress__item_content.slds-grid_align-spread.slds-grid > .slds-grid_align-end.slds-size_1-of-4.slds-grid > .slds-media__figure_reverse.slds-media__figure > .slds-form-element > label[for="substep-incomplete-0-action"] > input') to have no violations:

    <input aria-describedby="substep-incomplete-0-action-desc" id="substep-incomplete-0-action" type="checkbox">

    Expected the HTML found at $('#card-step-5-progress-indicator > .slds-progress__list.slds-progress__list-bordered > .slds-is-active.slds-progress__item > .slds-progress__item_content.slds-grid_align-spread.slds-grid > .slds-grid_align-end.slds-size_1-of-4.slds-grid > .slds-media__figure_reverse.slds-media__figure > .slds-form-element > label[for="substep-incomplete-0-action"] > input') to have no violations:

    <input aria-describedby="substep-incomplete-0-action-desc" id="substep-incomplete-0-action" type="checkbox">

    Received:

    "Form field must not have multiple label elements (form-field-multiple-labels)"

    Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.2/form-field-multiple-labels?application=axeAPI

      85 | 					},
      86 | 				})
    > 87 | 			).toHaveNoViolations();
         | 			  ^
      88 | 		},
      89 | 	});
      90 | });

      at _callee$ (tests/story-based-tests.accessibility-test.js:87:6)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (tests/story-based-tests.accessibility-test.js:32:103)
      at _next (tests/story-based-tests.accessibility-test.js:34:194)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 2 passed, 4 total
Snapshots:   0 total
Time:        36.325s, estimated 81s
```

**Comment by interactivellama** [comment]
@jcjuett This is one is broken out now.
