### ISSUE TITLE
Getting this test failed when I run npm test 

### ISSUE THREAD

**Issue by keshavg2** [salesforce/design-system-react#2463]
FAIL  components/date-picker/__tests__/datepicker.dom-snapshot-test.jsx
[test:dom-snapshot]   ● Console
[test:dom-snapshot] 
[test:dom-snapshot]     console.warn tests/console-message-overrides.js:10
[test:dom-snapshot]       
[test:dom-snapshot]     console.error tests/console-message-overrides.js:5
[test:dom-snapshot]       
[test:dom-snapshot] 
[test:dom-snapshot]   ● Datepicker Default DOM Snapshot
[test:dom-snapshot] 
[test:dom-snapshot]     Warning: componentWillUpdate has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.
[test:dom-snapshot] 
[test:dom-snapshot]     * Move data fetching code or side effects to componentDidUpdate.
[test:dom-snapshot]     * Rename componentWillUpdate to UNSAFE_componentWillUpdate to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
[test:dom-snapshot] 
[test:dom-snapshot]     Please update the following components: SLDSDialog
[test:dom-snapshot] 
[test:dom-snapshot]        9 | 	console.warn = function(message) {
[test:dom-snapshot]       10 | 		warn.apply(console, args);
[test:dom-snapshot]     > 11 | 		throw message instanceof Error ? message : new Error(message);
[test:dom-snapshot]          | 		                                           ^
[test:dom-snapshot]       12 | 	};
[test:dom-snapshot]       13 | 
[test:dom-snapshot]       14 | 	return { error, errorNew: console.error, warn, warnNew: console.warn };
[test:dom-snapshot] 
[test:dom-snapshot]       at BufferedConsole.console.warn (tests/console-message-overrides.js:11:46)
[test:dom-snapshot]       at printWarning (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2256:15)
[test:dom-snapshot]       at lowPriorityWarningWithoutStack (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2277:20)
[test:dom-snapshot]       at Object.<anonymous>.ReactStrictModeWarnings.flushPendingUnsafeLifecycleWarnings (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2453:7)
[test:dom-snapshot]       at flushRenderPhaseStrictModeWarningsInDEV (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15699:31)
[test:dom-snapshot]       at commitRootImpl (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14947:3)
[test:dom-snapshot]       at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:697:12)
[test:dom-snapshot]       at runWithPriority (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2013:10)
[test:dom-snapshot]       at commitRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14932:3)
[test:dom-snapshot]       at finishSyncRender (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14439:3)
[test:dom-snapshot] 
[test:dom-snapshot]   ● Datepicker Default HTML Snapshot
[test:dom-snapshot] 
[test:dom-snapshot]     Warning: A future version of React will block javascript: URLs as a security precaution. Use event handlers instead if you can. If you need to generate unsafe HTML try using dangerouslySetInnerHTML instead. React was passed %s.%s
[test:dom-snapshot] 
[test:dom-snapshot]       4 | 	console.error = function(message) {
[test:dom-snapshot]       5 | 		error.apply(console, args);
[test:dom-snapshot]     > 6 | 		throw message instanceof Error ? message : new Error(message);
[test:dom-snapshot]         | 		                                           ^
[test:dom-snapshot]       7 | 	};
[test:dom-snapshot]       8 | 
[test:dom-snapshot]       9 | 	console.warn = function(message) {
[test:dom-snapshot] 
[test:dom-snapshot]       at BufferedConsole.console.error (tests/console-message-overrides.js:6:46)
[test:dom-snapshot]       at warningWithoutStack (node_modules/react-dom/cjs/react-dom-server.node.development.js:76:32)
[test:dom-snapshot]       at warning (node_modules/react-dom/cjs/react-dom-server.node.development.js:155:27)
[test:dom-snapshot]       at sanitizeURL (node_modules/react-dom/cjs/react-dom-server.node.development.js:908:5)
[test:dom-snapshot]       at createMarkupForProperty (node_modules/react-dom/cjs/react-dom-server.node.development.js:1056:9)
[test:dom-snapshot]       at createOpenTagMarkup (node_modules/react-dom/cjs/react-dom-server.node.development.js:3079:16)
[test:dom-snapshot]       at ReactDOMServerRenderer.renderDOM (node_modules/react-dom/cjs/react-dom-server.node.development.js:4179:15)
[test:dom-snapshot]       at ReactDOMServerRenderer.render (node_modules/react-dom/cjs/react-dom-server.node.development.js:3647:21)
[test:dom-snapshot]       at ReactDOMServerRenderer.read (node_modules/react-dom/cjs/react-dom-server.node.development.js:3536:29)
[test:dom-snapshot]       at Object.renderToStaticMarkup (node_modules/react-dom/cjs/react-dom-server.node.development.js:4261:27)
[test:dom-snapshot] 
[test:dom-snapshot]  PASS  components/panel/__tests__/filtering.dom-snapshot-test.jsx
[lint] [lint:style] [1] npx prettylint *.json exited with code 0
[test:dom-snapshot]  FAIL  tests/story-based-tests.dom-snapshot-test.js
[test:dom-snapshot]   ● Test suite failed to run
[test:dom-snapshot] 
[test:dom-snapshot]     /home/keshav/design-system-react/.storybook/babel.config.js:1
[test:dom-snapshot]     import babelConfig from '../babel.config.js';
[test:dom-snapshot]            ^^^^^^^^^^^
[test:dom-snapshot] 
[test:dom-snapshot]     SyntaxError: Unexpected identifier
[test:dom-snapshot] 
[test:dom-snapshot]       at getBabelRC (node_modules/babel-jest/build/index.js:104:43)
[test:dom-snapshot] 
[test:dom-snapshot] Test Suites: 2 failed, 1 passed, 3 total
[test:dom-snapshot] Tests:       2 failed, 5 passed, 7 total
[test:dom-snapshot] Snapshots:   5 passed, 5 total
[test:dom-snapshot] Time:        6.764s
[test:dom-snapshot] Ran all test suites.
[test:dom-snapshot] npm ERR! code ELIFECYCLE
npm ERR! errno 1
[test:dom-snapshot] npm ERR! design-system-react@0.10.17 test:dom-snapshot: `cross-env NODE_ENV=test npx jest --runInBand --config=tests/story-based-tests.dom-snapshot-test.config.json`
[test:dom-snapshot] npm ERR! Exit status 1
[test:dom-snapshot] npm ERR! 
[test:dom-snapshot] npm ERR! Failed at the design-system-react@0.10.17 test:dom-snapshot script.
[test:dom-snapshot] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[test:dom-snapshot] 
[test:dom-snapshot] npm ERR! A complete log of this run can be found in:
[test:dom-snapshot] npm ERR!     /home/keshav/.npm/_logs/2020-02-10T22_05_18_913Z-debug.log
[test:dom-snapshot] npm run test:dom-snapshot exited with code 1
[test:accessibility] ERR! => Error parsing babel config file: /home/keshav/design-system-react/.storybook/babel.config.js
[test:accessibility] ERR!       
[test:accessibility] ERR!       We tried both loading as JS & JSON, neither worked.
[test:accessibility] ERR!       Maybe there's a syntax error in the file?
[test:accessibility] ERR! => From JS loading we got: Unexpected identifier
[test:accessibility] ERR! => From JSON loading we got: JSON5: invalid character 'i' at 1:1
[test:accessibility] (node:15343) UnhandledPromiseRejectionWarning: /home/keshav/design-system-react/.storybook/babel.config.js:1
[test:accessibility] import babelConfig from '../babel.config.js';
[test:accessibility]        ^^^^^^^^^^^
[test:accessibility] 
[test:accessibility] SyntaxError: Unexpected identifier
[test:accessibility]     at Module._compile (internal/modules/cjs/loader.js:721:23)
[test:accessibility]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
[test:accessibility]     at Module.load (internal/modules/cjs/loader.js:653:32)
[test:accessibility]     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[test:accessibility]     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[test:accessibility]     at Module.require (internal/modules/cjs/loader.js:690:17)
[test:accessibility]     at require (internal/modules/cjs/helpers.js:25:18)
[test:accessibility]     at loadFromPath (/home/keshav/design-system-react/node_modules/@storybook/core/dist/server/utils/load-custom-babel-config.js:48:16)
[test:accessibility]     at _default (/home/keshav/design-system-react/node_modules/@storybook/core/dist/server/utils/load-custom-babel-config.js:115:85)
[test:accessibility]     at Object.babel (/home/keshav/design-system-react/node_modules/@storybook/core/dist/server/common/common-preset.js:21:45)
[test:accessibility]     at accumulationPromise.then.newConfig (/home/keshav/design-system-react/node_modules/@storybook/core/dist/server/presets.js:261:72)
[test:accessibility]     at process._tickCallback (internal/process/next_tick.js:68:7)
[test:accessibility]     at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
[test:accessibility]     at findNodeScript.then.existing (/usr/local/lib/node_modules/npm/node_modules/libnpx/index.js:268:14)
[test:accessibility] (node:15343) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
[test:accessibility] (node:15343) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[4] # Generating docs based on `components` object in `package.json`. Please add any public components to this object.
[4] [ ./components/accordion/index.jsx ] 
[4]   dependency input path:
[4]    './components/accordion/panel.jsx'
[4] [ ./components/alert/index.jsx ] 
[4]   dependency input path:
[4]    './components/alert/container.jsx'
[4] [ ./components/app-launcher/index.jsx ] 
[4]   dependency input path:
[4]    './components/app-launcher/expandable-section.jsx'
[4]   dependency input path:
[4]    './components/app-launcher/link.jsx'
[4]   dependency input path:
[4]    './components/app-launcher/tile.jsx'
[4] [ ./components/avatar/index.jsx ] 
[4] [ ./components/badge/index.jsx ] 
[4] [ ./components/brand-band/index.jsx ] 
[4] [ ./components/breadcrumb/index.jsx ] 
[4] [ ./components/builder-header/index.jsx ] 
[4]   dependency input path:
[4]    './components/builder-header/nav.jsx'
[4]   dependency input path:
[4]    './components/builder-header/nav-dropdown.jsx'
[4]   dependency input path:
[4]    './components/builder-header/nav-link.jsx'
[4]   dependency input path:
[4]    './components/builder-header/toolbar.jsx'
[4] [ ./components/button-group/index.jsx ] 
[4] [ ./components/button-stateful/index.jsx ] 
[4] [ ./components/button/index.jsx ] 
[4] [ ./components/card/index.jsx ] 
[4]   dependency input path:
[4]    './components/card/empty.jsx'
[4]   dependency input path:
[4]    './components/card/filter.jsx'
[4] [ ./components/carousel/index.jsx ] 
[4] [ ./components/checkbox/index.jsx ] 
[test:accessibility]  FAIL  tests/story-based-tests.accessibility-test.js (13.859s)
[test:accessibility]   aXe storyshots
[test:accessibility]     ✕ encountered a declaration exception (3ms)
[test:accessibility] 
[test:accessibility]   ● aXe storyshots › encountered a declaration exception
[test:accessibility] 
[test:accessibility]     /home/keshav/design-system-react/.storybook/babel.config.js:1
[test:accessibility]     import babelConfig from '../babel.config.js';
[test:accessibility]            ^^^^^^^^^^^
[test:accessibility] 
[test:accessibility]     SyntaxError: Unexpected identifier
[test:accessibility] 
[test:accessibility]       at getBabelRC (node_modules/babel-jest/build/index.js:104:43)
[test:accessibility] 
[4] [ ./components/color-picker/index.jsx ] 
[test:accessibility]   console.log tests/story-based-tests.accessibility-test.js:39
[test:accessibility]     
[test:accessibility]     ★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★
[test:accessibility]     QUEUEING: STORY-BASED Accessibility SNAPSHOT TESTING
[test:accessibility]     ★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★☆★
[test:accessibility]     
[test:accessibility]     EXECUTING /tests/story-based-accessibility-tests.js
[test:accessibility]     
[test:accessibility]     This script uses Jest to call aXe https://github.com/dequelabs/axe-core on each Storybook story found at http://localhost:9001. This is static testing of the DOM on load. If you need an open menu tested, then you will need to open the menu with the `isOpen` prop.
[test:accessibility]     
[test:accessibility]     For more information, please review: https://github.com/salesforce/design-system-react/blob/master/tests/README.md
[test:accessibility]     
[test:accessibility] 
[test:accessibility]   console.log tests/story-based-tests.accessibility-test.js:62
[test:accessibility]     Shutting down the server running Storybook
[test:accessibility] 
[test:accessibility] Test Suites: 1 failed, 1 total
[test:accessibility] Tests:       1 failed, 1 total
[test:accessibility] Snapshots:   0 total
[test:accessibility] Time:        14.813s
[test:accessibility] Ran all test suites.
[test:accessibility] npm ERR! code ELIFECYCLE
[test:accessibility] npm ERR! errno 1
[test:accessibility] npm ERR! design-system-react@0.10.17 test:accessibility: `cross-env NODE_ENV=testwithrequirehook PORT=8002 npm run static:build && npx jest --runInBand --config=tests/story-based-tests.accessibility-test.config.json`
[test:accessibility] npm ERR! Exit status 1
[test:accessibility] npm ERR! 
[test:accessibility] npm ERR! Failed at the design-system-react@0.10.17 test:accessibility script.
[test:accessibility] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[test:accessibility] 
[test:accessibility] npm ERR! A complete log of this run can be found in:
[test:accessibility] npm ERR!     /home/keshav/.npm/_logs/2020-02-10T22_05_38_642Z-debug.log
[test:accessibility] npm run test:accessibility exited with code 1
[4] [ ./components/combobox/combobox.jsx ] 
[4] [ ./components/data-table/index.jsx ] 
[4]   dependency input path:
[4]    './components/data-table/cell.jsx'
[4]   dependency input path:
[4]    './components/data-table/column.jsx'
[4]   dependency input path:
[4]    './components/data-table/highlight-cell.jsx'
[4]   dependency input path:
[4]    './components/data-table/row-actions.jsx'
[4] [ ./components/date-picker/date-picker.jsx ] 
[4] [ ./components/dynamic-icon/index.jsx ] 
[4] [ ./components/expandable-section/index.jsx ] 
[4] [ ./components/expression/index.jsx ] 
[4]   dependency input path:
[4]    './components/expression/condition.jsx'
[4]   dependency input path:
[4]    './components/expression/formula.jsx'
[4]   dependency input path:
[4]    './components/expression/group.jsx'
[4] [ ./components/files/index.jsx ] 
[4]   dependency input path:
[4]    './components/files/file.jsx'
[4]   dependency input path:
[4]    './components/files/more-files.jsx'
[4] [ ./components/filter/index.jsx ] 
[4] [ ./components/global-header/index.jsx ] 
[4]   dependency input path:
[4]    './components/global-header/favorites.jsx'
[4]   dependency input path:
[4]    './components/global-header/help.jsx'
[4]   dependency input path:
[4]    './components/global-header/notifications.jsx'
[4]   dependency input path:
[4]    './components/global-header/profile.jsx'
[4]   dependency input path:
[4]    './components/global-header/search.jsx'
[4]   dependency input path:
[4]    './components/global-header/setup.jsx'
[4]   dependency input path:
[4]    './components/global-header/task.jsx'
[4] [ ./components/global-navigation-bar/index.jsx ] 
[4]   dependency input path:
[4]    './components/global-navigation-bar/button.jsx'
[4]   dependency input path:
[4]    './components/global-navigation-bar/dropdown.jsx'
[4]   dependency input path:
[4]    './components/global-navigation-bar/label.jsx'
[4]   dependency input path:
[4]    './components/global-navigation-bar/link.jsx'
[4]   dependency input path:
[4]    './components/global-navigation-bar/region.jsx'
[4] [ ./components/icon-settings/index.jsx ] 
[4] [ ./components/icon/index.jsx ] 
[4] [ ./components/input/index.jsx ] 
[4]   dependency input path:
[4]    './components/input/search.jsx'
[4] [ ./components/location-map/index.jsx ] 
[4] [ ./components/media-object/index.jsx ] 
[4] [ ./components/menu-dropdown/menu-dropdown.jsx ] 
[4]   dependency input path:
[4]    './components/menu-dropdown/button-trigger.jsx'
[4] [ ./components/modal/index.jsx ] 
[4] [ ./components/page-header/index.jsx ] 
[4]   dependency input path:
[4]    './components/page-header/control.jsx'
[4] [ ./components/panel/index.jsx ] 
[4]   dependency input path:
[4]    './components/panel/filtering/group.jsx'
[4]   dependency input path:
[4]    './components/panel/filtering/list-heading.jsx'
[4]   dependency input path:
[4]    './components/panel/filtering/list.jsx'
[4] [ ./components/pill-container/index.jsx ] 
[4] [ ./components/pill/index.jsx ] 
[4] [ ./components/popover/popover.jsx ] 
[4] [ ./components/progress-bar/index.jsx ] 
[4] [ ./components/progress-indicator/index.jsx ] 
[4] [ ./components/progress-ring/index.jsx ] 
[4] [ ./components/radio-button-group/index.jsx ] 
[4] [ ./components/radio-group/index.jsx ] 
[4] [ ./components/radio/index.jsx ] 
[4] [ ./components/scoped-notification/index.jsx ] 
[4] [ ./components/setup-assistant/index.jsx ] 
[4]   dependency input path:
[4]    './components/setup-assistant/step.jsx'
[4] [ ./components/slider/index.jsx ] 
[4] [ ./components/spinner/index.jsx ] 
[4] [ ./components/split-view/index.jsx ] 
[4]   dependency input path:
[4]    './components/split-view/header.jsx'
[4]   dependency input path:
[4]    './components/split-view/listbox.jsx'
[4] [ ./components/tabs/index.jsx ] 
[4]   dependency input path:
[4]    './components/tabs/panel.jsx'
[4] [ ./components/textarea/index.jsx ] 
[4] [ ./components/time-picker/index.jsx ] 
[4] [ ./components/toast/index.jsx ] 
[4]   dependency input path:
[4]    './components/toast/container.jsx'
[4] [ ./components/tooltip/index.jsx ] 
[4] [ ./components/tree/index.jsx ] 
[4] [ ./components/trial-bar/index.jsx ] 
[4]   dependency input path:
[4]    './components/trial-bar/button.jsx'
[4]   dependency input path:
[4]    './components/trial-bar/dropdown.jsx'
[4] [ ./components/vertical-navigation/index.jsx ] 
[4] [ ./components/visual-picker/index.jsx ] 
[4]   dependency input path:
[4]    './components/visual-picker/link.jsx'
[4] [ ./components/welcome-mat/index.jsx ] 
[4]   dependency input path:
[4]    './components/welcome-mat/info-badge.jsx'
[4]   dependency input path:
[4]    './components/welcome-mat/tile.jsx'
[4] 
[4] > design-system-react@0.10.17 test:docs /home/keshav/design-system-react
[4] > npx babel-node ./tests/component-docs-test.js
[4] 
[lint] [lint:style] [0] npx prettier --list-different **/*.{js,jsx} exited with code 0
[lint] [lint:style] npm run lint:style exited with code 0
[4] 
[4] 
[4] =========================================================
[4] Checking component docs JSON for empty strings
[4] =========================================================
[4] 
[4] npm run build:docs && npm run test:docs exited with code 0
[lint] [lint:quality] 
[lint] [lint:quality] /home/keshav/design-system-react/components/button-stateful/__tests__/button-stateful.browser-test.jsx
[lint] [lint:quality]   27:21  error  Do not depend on the return value from ReactDOM.render  react/no-render-return-value
[lint] [lint:quality] 
[lint] [lint:quality] /home/keshav/design-system-react/components/card/__tests__/card.browser-test.jsx
[lint] [lint:quality]   53:21  error  Do not depend on the return value from ReactDOM.render  react/no-render-return-value
[lint] [lint:quality] 
[lint] [lint:quality] /home/keshav/design-system-react/components/checkbox/index.jsx
[lint] [lint:quality]   293:8  error  Curly braces are unnecessary here  react/jsx-curly-brace-presence
[lint] [lint:quality]   360:7  error  Curly braces are unnecessary here  react/jsx-curly-brace-presence
[lint] [lint:quality] 
[lint] [lint:quality] /home/keshav/design-system-react/components/combobox/__tests__/combobox.browser-test.jsx
[lint] [lint:quality]   123:2  error  componentWillUpdate is deprecated since React 16.9.0, use UNSAFE_componentWillUpdate instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillupdate. Use https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles to automatically update your components  react/no-deprecated
[lint] [lint:quality] 
[lint] [lint:quality] /home/keshav/design-system-react/components/data-table/__tests__/data-table.browser-test.jsx
[lint] [lint:quality]   87:21  error  Do not depend on the return value from ReactDOM.render  react/no-render-return-value
[lint] [lint:quality] 
[lint] [lint:quality] /home/keshav/design-system-react/components/date-picker/private/calendar-wrapper.jsx
[lint] [lint:quality]   20:2  error  defaultProps should be placed after propTypes  react/sort-comp
[lint] [lint:quality] 
[lint] [lint:quality] /home/keshav/design-system-react/components/expression/index.jsx
[lint] [lint:quality]   91:2  error  componentWillMount is deprecated since React 16.9.0, use UNSAFE_componentWillMount instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillmount. Use https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles to automatically update your components  react/no-deprecated
[lint] [lint:quality] 
[lint] [lint:quality] /home/keshav/design-system-react/components/files/file.jsx
[lint] [lint:quality]   127:2  error  componentWillMount is deprecated since React 16.9.0, use UNSAFE_componentWillMount instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillmount. Use https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles to automatically update your components  react/no-deprecated
[lint] [lint:quality] 
[lint] [lint:quality] /home/keshav/design-system-react/components/files/index.jsx
[lint] [lint:quality]   49:2  error  componentWillMount is deprecated since React 16.9.0, use UNSAFE_componentWillMount instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillmount. Use https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles to automatically update your components  react/no-deprecated
[lint] [lint:quality] 
[lint] [lint:quality] /home/keshav/design-system-react/components/files/more-files.jsx
[lint] [lint:quality]   74:2  error  componentWillMount is deprecated since React 16.9.0, use UNSAFE_componentWillMount instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillmount. Use https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles to automatically update your components  react/no-deprecated
[lint] [lint:quality] 
[lint] [lint:quality] /home/keshav/design-system-react/components/forms/input/__tests__/inline.browser-test.jsx
[lint] [lint:quality]   19:21  error  Do not depend on the return value from ReactDOM.render  react/no-render-return-value
[lint] [lint:quality] 
[lint] [lint:quality] /home/keshav/design-system-react/components/forms/private/label.jsx
[lint] [lint:quality]   52:7  error  Curly braces are unnecessary here  react/jsx-curly-brace-presence
[lint] [lint:quality] 
[lint] [lint:quality] /home/keshav/design-system-react/components/location-map/__tests__/location-map.browser-test.jsx
[lint] [lint:quality]   43:18  error  Do not depend on the return value from ReactDOM.render  react/no-render-return-value
[lint] [lint:quality] 
[lint] [lint:quality] /home/keshav/design-system-react/components/menu-picklist/index.jsx
[lint] [lint:quality]   197:2  error  componentWillMount is deprecated since React 16.9.0, use UNSAFE_componentWillMount instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillmount. Use https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles to automatically update your components  react/no-deprecated
[lint] [lint:quality] 
[lint] [lint:quality] /home/keshav/design-system-react/components/modal/__tests__/modal.browser-test.jsx
[lint] [lint:quality]   51:18  error  Do not depend on the return value from ReactDOM.render  react/no-render-return-value
[lint] [lint:quality] 
[lint] [lint:quality] /home/keshav/design-system-react/components/radio-group/index.jsx
[lint] [lint:quality]   141:8  error  Curly braces are unnecessary here  react/jsx-curly-brace-presence
[lint] [lint:quality] 
[lint] [lint:quality] /home/keshav/design-system-react/components/radio/index.jsx
[lint] [lint:quality]   141:2  error  componentWillMount is deprecated since React 16.9.0, use UNSAFE_componentWillMount instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillmount. Use https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles to automatically update your components  react/no-deprecated
[lint] [lint:quality] 
[lint] [lint:quality] /home/keshav/design-system-react/components/spinner/__tests__/spinner.browser-test.jsx
[lint] [lint:quality]   15:21  error  Do not depend on the return value from ReactDOM.render  react/no-render-return-value
[lint] [lint:quality] 
[lint] [lint:quality] /home/keshav/design-system-react/components/textarea/index.jsx
[lint] [lint:quality]   291:9  error  Curly braces are unnecessary here  react/jsx-curly-brace-presence
[lint] [lint:quality] 
[lint] [lint:quality] /home/keshav/design-system-react/components/utilities/dialog/index.jsx
[lint] [lint:quality]   215:2  error  componentWillUpdate is deprecated since React 16.9.0, use UNSAFE_componentWillUpdate instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillupdate. Use https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles to automatically update your components  react/no-deprecated
[lint] [lint:quality] 
[lint] [lint:quality] /home/keshav/design-system-react/components/utilities/label/index.jsx
[lint] [lint:quality]   64:7  error  Curly braces are unnecessary here  react/jsx-curly-brace-presence
[lint] [lint:quality] 
[lint] [lint:quality] /home/keshav/design-system-react/components/visual-picker/index.jsx
[lint] [lint:quality]   64:2  error  componentWillMount is deprecated since React 16.9.0, use UNSAFE_componentWillMount instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillmount. Use https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles to automatically update your components  react/no-deprecated
[lint] [lint:quality] 
[lint] [lint:quality] /home/keshav/design-system-react/components/welcome-mat/__tests__/welcome-mat.browser-test.jsx
[lint] [lint:quality]   46:18  error  Do not depend on the return value from ReactDOM.render  react/no-render-return-value
[lint] [lint:quality] 
[lint] [lint:quality] /home/keshav/design-system-react/components/welcome-mat/index.jsx
[lint] [lint:quality]   100:2  error  componentWillMount is deprecated since React 16.9.0, use UNSAFE_componentWillMount instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillmount. Use https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles to automatically update your components  react/no-deprecated
[lint] [lint:quality] 
[lint] [lint:quality] /home/keshav/design-system-react/components/welcome-mat/info-badge.jsx
[lint] [lint:quality]   62:2  error  componentWillMount is deprecated since React 16.9.0, use UNSAFE_componentWillMount instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillmount. Use https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles to automatically update your components  react/no-deprecated
[lint] [lint:quality] 
[lint] [lint:quality] /home/keshav/design-system-react/components/welcome-mat/tile.jsx
[lint] [lint:quality]   84:2  error  componentWillMount is deprecated since React 16.9.0, use UNSAFE_componentWillMount instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillmount. Use https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles to automatically update your components  react/no-deprecated
[lint] [lint:quality] 
[lint] [lint:quality] ✖ 27 problems (27 errors, 0 warnings)
[lint] [lint:quality]   6 errors, 0 warnings potentially fixable with the `--fix` option.
[lint] [lint:quality] 
[lint] [lint:quality] npm ERR! code ELIFECYCLE
npm ERR! errno 1
[lint] [lint:quality] npm ERR! design-system-react@0.10.17 lint:quality: `npx eslint "**/*.{jsx,js,json}" --max-warnings=0`
[lint] [lint:quality] npm ERR! Exit status 1
[lint] [lint:quality] npm ERR! 
[lint] [lint:quality] npm ERR! Failed at the design-system-react@0.10.17 lint:quality script.
[lint] [lint:quality] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[lint] [lint:quality] 
[lint] [lint:quality] npm ERR! A complete log of this run can be found in:
[lint] [lint:quality] npm ERR!     /home/keshav/.npm/_logs/2020-02-10T22_07_06_014Z-debug.log
[lint] [lint:quality] npm run lint:quality exited with code 1

**Comment by keshavg2** [comment]
Can Anyone please help me to solve this?
